# Sample for ttn-abp example on Raspberry Pi
# Caution: requires bcm2835 library to be already installed
# http://www.airspayce.com/mikem/bcm2835/

BIN=get_deveui

LIBDIR=../
all: $(BIN)
include ../Makefile.env
